### ISSUE TITLE
Please url encode the account information

### ISSUE THREAD

**Issue by philpott** [audienceproject/userreport-tag-template#1]
https://github.com/audienceproject/userreport-tag-template/blob/ac998fecde9e3bd94800d8fb7937dcbc23ba1e48/template.tpl#L60

Looking at your template account ID parameter restrictions it should only consist of valid url characters, you should still url encode the parameter value to follow best practices -- and future proof your template.

Thanks
Michael

**Comment by romanych** [comment]
@philpott , thank you for bringing this to our attention.

We have RegEx validation rule for this parameter (https://github.com/audienceproject/userreport-tag-template/commit/e3d3afcf8cba93e191b329536142b670e9086f5c#diff-b9e8d7509e6565e274ccef1aec078079R33-R49), however it is definitely cleaner solution to encode URL component. Added `encodeUriComponent` in 7e18611d0a25082986a21a63e663de49423a82ca
